<?php

declare(strict_types=1);

namespace Src\Catalog\Application\ImageStorage;

/**
 * Port for S3-compatible image storage. Infrastructure implements this.
 * The domain only ever sees the storage key (a string); URLs are derived here.
 */
interface ImageStorage
{
    /**
     * Stores the file at $tempPath under $prefix and returns the storage key.
     * The key is generated by the implementation (uuid + mime-derived ext).
     * The client-supplied filename is never used.
     *
     * @param  string  $prefix  e.g. "products/1/colors/3"
     */
    public function store(string $tempPath, string $mimeType, string $prefix): string;

    public function delete(string $storageKey): void;

    public function url(string $storageKey): string;
}
